### PR TITLE
Testing - searching notes

### PR DESCRIPTION
**Pull request by BrettKoenig04**

### CODE REVIEW

**Review by abdala2020 — DISMISSED** [review]
Hey Bret, the test is failing because in testing_note.json fixture file doesn't match Django serialization format. the bug is in line 22 - the photo field. It syntax error. I think you mistakenly forget to put a comma

**Comment by abdala2020** [comment]
Sorry, Brett, actually the comma is missing in multiple places.  other than that the code is passing.

**Comment by BrettKoenig04** [comment]
> Sorry, Brett, actually the comma is missing in multiple places. other than that the code is passing.

I wonder when the fixtures were made cause I never had issues with before. I will fix and add those changes to the pull request though, thanks for letting me know.

**Comment by xd3262nd** [comment]
I have made some changes on the testing as well here #53 which fixed some of the errors that yours have

**Review by xd3262nd — APPROVED** [review]

**Review by xd3262nd — APPROVED** [review]

**Review by xd3262nd — APPROVED** [review]

**Pull request merged**
