### PR TITLE
Add user profile to User model and added functionality to modify the user profile

### LINKED ISSUE #6: Store more information about users
Create public profile, which could include social media usernames; favorite bands, which notes represent their favorite shows, what else?

See also #6

### LINKED ISSUE #10: Ability for users to edit own profile page

### PR DESCRIPTION
**Pull request by xd3262nd**
Related to issues #10  and #6

### CODE REVIEW

**Comment by xd3262nd** [comment]
Please remember to run `pip install -r requirements.txt` to install the required packages. Also refer to this thread as well https://mctc-itec.slack.com/archives/C01F5RZELHW/p1606482612000100?thread_ts=1606271176.021700&cid=C01F5RZELHW

**Comment by abdala2020** [comment]
@xd3262nd  tested user profile and their ability to update it. looks great. However, regarding the info on their profile (favorite artist, venue, and show), is this info supposed to be based on the artist/show/venue that has already been rated either by the owner of the profile or other users?  because right now, I can put just (aaaaaaa) in all fields and it will be updated. my other question is: is this a public profile, if any user clicks another user, will they be able to see their profile.?

**Comment by xd3262nd** [comment]
@abdala2020  The user can put whatever artist/show/venue that they want, I am not sure if we need to showcase the functionaility to add valid artist so far. As for the profile, it is private so far but we can add the functionality so everyone can look into their profile when they click on the user name on the notes section

**Comment by abdala2020** [comment]
@xd3262nd  Thanks for clarifying.

**Review by abdala2020 — COMMENTED** [review]
I think this is good. I Tested it. Users can store info on their profile. users can update their profiles.

**Review by abdala2020 — APPROVED** [review]
approved! good to merge!

**Pull request merged**
